### ISSUE TITLE
AttributeError: module 'simplefix' has no attribute 'Message'

### ISSUE THREAD

**Issue by irmscher9** [da4089/simplefix#29]
import simplefix

fix_msg = simplefix.Message()

_Traceback (most recent call last):
  File "C:/Users/irmsc/pp/simple_fix_test/main.py", line 3, in <module>
    fix_msg = simplefix.Message()
AttributeError: module 'simplefix' has no attribute 'Message'_

**Comment by da4089** [comment]
The message class is actually called "FixMessage", so the line above should be "fix_msg = simplefix.FixMessage()".

Do you copy that line from somewhere?   I'd like to fix that mistake in any documentation, or wherever.

**Comment by irmscher9** [comment]
> The message class is actually called "FixMessage", so the line above should be "fix_msg = simplefix.FixMessage()".
> 
> Do you copy that line from somewhere? I'd like to fix that mistake in any documentation, or wherever.

Yes, from here: https://simplefix.readthedocs.io/en/latest/import.html

**Comment by vargaspazdaniel** [comment]
I have the same error, I just installed the package, made the import and try to set
`fix_msg = simplefix.Message()`
But I'm getting an error.

**Comment by da4089** [comment]
I've pushed the latest documentation to readthedocs, which corrects this.
The message class is "FixMessage", not "Message".
