### ISSUE TITLE
Checksum is not always 3 ASCII characters

### ISSUE THREAD

**Issue by hptabster** [da4089/simplefix#58]
The FIX protocol specifies that the checjsum should be 3 ASCII characters. I am observing that simplefix (1.0.16) sometimes sends less, i.e., 2 characters:
2023-09-11 13:16:44,485 : process_buffer : INFO : Sending FIX heartbeat message 8=FIX.4.4|9=67|35=0|49=QAORG1_UAT|56=STP_ROUTER_UAT|34=2|52=20230911-17:16:44.485|**10=88**

**Comment by hptabster** [comment]
Update this [code](https://github.com/da4089/simplefix/blob/e46841b1514accc6d772a385800d7a8dabd0b43b/simplefix/message.py#L573)
to a formatted f-string that is always 3 digits:
**f"{checksum % 256:0>3}"**

**Comment by da4089** [comment]
Thanks for the report.  Fixed in v1.0.17, now on PyPI.
