### ISSUE TITLE
Add ability to "append" header tags separately (if necessary)

### ISSUE THREAD

**Issue by dcdillon** [da4089/simplefix#8]
I am trying to use simplefix to create a very simple FIX engine implementation in pure Python.

Would you be accepting of some code that allows the user, when building a message, to add tags to the front of the tag list (i.e. header tags).  To actually use this in a FIX engine implementation, one needs to be able to add the sequence number (34) and sending time (52) right before the message is sent (not when the bulk of the message is created).

I'm happy to write the code, but wanted to know if you'd accept it as a PR or if you'd rather I simply forked things.

**Comment by da4089** [comment]
Sorry for the slow response -- I'm happy to accept a pull request or suggested code.
Or I could add it myself -- it seems like a reasonable request.

**Comment by dcdillon** [comment]
I was thinking it'd work just fine if there was a Boolean flag on the add methods that said add at front or add at back (defaulting to back).  That would be sufficient.  I can get to it tomorrow night if that's an agreeable method.

**Comment by da4089** [comment]
I haven't thought it through properly yet.
I'm not sure what the interaction with raw mode should be.

**Comment by da4089** [comment]
Another option might be to allow the value of an existing tag to be over-written.  You could append 34 and 52 with bogus values, and then overwrite them just before encoding.
It's less simple when considering repeating groups however.
And I'm not sure it's the best thing anyway.

**Comment by da4089** [comment]
Daniel, I've pushed a change with an added 'header' flag.  Can you please check it works for your application?

**Comment by dcdillon** [comment]
I will check it this morning.  Thanks!
