### ISSUE TITLE
Add support for FIX 4.4

### ISSUE THREAD

**Issue by talaniz** [da4089/simplefix#9]
4.2 is quite common, but I notice in the tests that there doesn't seem to be any mention of version 4.4. I understand that this is a simple version, but even my employer now requires 4.4 as do many liquidity providers.

**Comment by da4089** [comment]
I think the current code should work for version 4.0 or later (including 5.0sp2 + extensions).
Did you find a problem trying to use 4.4 ?

**Comment by da4089** [comment]
Antonio,  I'm closing this because I think FIX.4.4 is fully supported.  There are a few of the test cases that use FIX.4.4 in the BeginString, and I know of no reason it won't work 100%.

If you run into a specific problem, please open an issue for that.

Thanks!
